### ISSUE TITLE
Add functionality to install with pip

### ISSUE THREAD

**Issue by ncywong** [Effective-Quadratures/Effective-Quadratures#160]

**Comment by psesh** [comment]
Do we need to upgrade the code to Python3 to make this work? See: https://packaging.python.org/tutorials/packaging-projects/

**Comment by psesh** [comment]
I'd had trouble getting ^^ to work on my machine with 2.7

**Comment by ncywong** [comment]
If you have not looked at this, it might help.
https://docs.python.org/2/distutils/

**Comment by psesh** [comment]
pip install equadratures should now work!
