### ISSUE TITLE
Convert all instances of np.matrix to np.ndarray

### ISSUE THREAD

**Issue by ncywong** [Effective-Quadratures/Effective-Quadratures#164]
It seems that np.matrix will be deprecated in the future. Thus, all instances of np.matrix should be changed to np.ndarray (e.g. the output of evaluatePolyFit)

In addition, we should stipulate that all 1-d outputs be represented by 1-d arrays instead of "column vectors" with size = (length, 1). It makes working with them more intuitive.

**Comment by smit-s** [comment]
@psesh  @ncywong  can I work on this issue. It seems to be unresolved since long. Can I try please?

**Comment by psesh** [comment]
@smit-s apologises, but I think this issue is long closed.
