### ISSUE TITLE
Saving a polynomial

### ISSUE THREAD

**Issue by psesh** [Effective-Quadratures/Effective-Quadratures#166]
In the implementation given below, the polynomial class needs to know the attributes of other classes--i.e., basis and parameter. It may be better if each of the other classes is endowed with **lxml** functionality. 

```

    def savePolynomial(self, filename):
        """
        Saves the polynomial as an xml file.

        :param Poly self:
            An instance of the Poly class.
        :param string filename:
            Path location and filename.

        """
        root = tree.Element("polynomial")
        polydoc = tree.SubElement(root, "equadratures")
        tree.SubElement(polydoc, "version_number").text = str(VERSION_NUMBER)
        tree.SubElement(polydoc, "date").text = str(time.strftime("%d/%m/%Y"))

        basisinfo = 

        polydoc_basis = tree.SubElement(root, "multi-index")
        tree.SubElement(polydoc_basis, "basis_type").text = str(self.basis.basis_type)
        tree.SubElement(polydoc_basis, "maximum_orders").text = str(self.basis.orders)

        polydoc_coefficients = tree.SubElement(root, "coefficients")
        tree.SubElement(polydoc_coefficients, "coefficients").text = str(self.coefficients)
        tree.SubElement(polydoc_coefficients, "index_set").text = str(self.basis.elements)

        polynomialobject = tree.ElementTree(root)
        polynomialobject.write(filename, pretty_print=True)
```

**Comment by veb7vmehra** [comment]
Hey @psesh I will like to work on this issue. Are there any prerequisites required?

**Comment by psesh** [comment]
Apologizes @veb7vmehra, this issue should have been closed ages ago. In terms of support, a basic understanding of polynomial approximations may be necessary to iron out some of the issues. That said, I think its worth creating an issue for better error detection. Will do that in a bit.

**Comment by psesh** [comment]
Apologizes @veb7vmehra, this issue should have been closed ages ago. In terms of support, a basic understanding of polynomial approximations may be necessary to iron out some of the issues. That said, please do fork / star the code so you will be made aware when issues are raised. Cheers!
