### ISSUE TITLE
Local import Issue with the parameter class

### ISSUE THREAD

**Issue by hz324** [Effective-Quadratures/Effective-Quadratures#182]
This could be an issue throughout the repository. However, I have only tried to import parameter.py , hence encountered this issue here.

<h3>Python Version:</h3>
python3.6.5

<h3>Encountered Error: </h3>
> File "/path/to/parameter.py", line 2, in \<module\>
>    from .distributions.gaussian import Gaussian
> ImportError: attempted relative import with no known parent package

<h3>Expected Behaviour:</h3>
No error returned for import

<h3>Reproduction steps:</h3>
change the current working directory to Effective-Quadratures/equadratures/
execute
> $ python3

In python console, type

> from parameter import Parameter

The error above should be encountered,
Note that doing

> from .parameter import Parameter

Should simply give
>  File "<stdin>", line 1
>    import .parameter as Parameter
>               ^
>SyntaxError: invalid syntax

**Comment by psesh** [comment]
Hi @hz324 

Following what you stated, I get the following error
```
ImportError: attempted relative import with no known parent package
>>> from .parameter import Parameter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named '__main__.parameter'; '__main__' is not a package
```
Can you move induced_distributions.py to the same folder as parameter.py please? Also, in your code replace

```
from .parameter import Parameter
from .poly import Poly
from equadratures import IndexSet
```
with
```
from .parameter import Parameter
from .poly import Poly
from .basis import Basis
```

**Comment by hz324** [comment]
Hi Pranay 
The file directory level is not the problem here.

I believe by doing
> from parameter import Parameter

The error of importing .distributions occurs.

And yes, I will update the importing scheme in the induced distribution once I can do imports :)

**Comment by hz324** [comment]
I don't think there's a clear solution to this issue. However, if a file is ever needed to run in it's current package level directory.

Do:
> python -m file.py

or:

>python -m distributions.file.py

for this particularly usage in the repo
