### ISSUE TITLE
Improvements to Parameter

### ISSUE THREAD

**Issue by psesh** [Effective-Quadratures/Effective-Quadratures#216]
Parameter should have a default `uniform` distribution and a default `order` of 1.

```
p = Parameter(lower=-1., upper=1.)
# TypeError: __init__() missing 2 required positional arguments: 'order' and 'distribution'
```

Parameter should take in a name in its constructor. If a name is not provided a default value of `'parameter'` can be assigned.

`horsepower = Parameter(name='horsepower', lower=180, upper=350)`

**Comment by PrayasJ** [comment]
Everything apart from distribution is done.  What lower and upper bounds should I take up for uniform distribution?

**Comment by psesh** [comment]
Lower and upper bounds must be user-defined values when no distribution is provided (and thus a uniform distribution is assumed).
