### ISSUE TITLE
Syntax improvements to Poly

### ISSUE THREAD

**Issue by psesh** [Effective-Quadratures/Effective-Quadratures#217]
`Poly` should facilitate rapid extrapolation. Rather than use

```
X2 = np.linspace(-1, 1., 100).reshape(100,1)
X = np.random.rand(20, 1)
y = X**2
p = Parameter(distribution='uniform', lower=-1., upper=1., order=3)
basis = Basis('univariate')
poly = Poly(p, basis, method='least-squares', sampling_args={'sample-points': X, 'sample-outputs': y})
poly.set_model()
f = poly.get_polyfit(X2)
```
It would simplfy workflows if `method='least-squares'` could be assumed by default, and the values in `sampling_args` could be provided as inputs permitting the following to work. Checks on the shape of `X` and `y` must ensure that the number of rows in `X` is equivalent to the number of rows in `y` and that `y` only has 1 column.

Also note that in the above the code should be OK with `sampling_args={'sample_points': X, 'sample_outputs': y}`

**Comment by veb7vmehra** [comment]
@psesh Sir what should we return if the checks on the shape that we are going to change aren't true for sample data?

**Comment by psesh** [comment]
Hi @veb7vmehra, an appropriate error message should do the trick. Cheers!

**Comment by veb7vmehra** [comment]
@psesh I have did the same thing but it isn't able to clear some checks with that

**Comment by veb7vmehra** [comment]
@psesh Sir any updates for me.

**Comment by psesh** [comment]
Can you let me know what specific errors you are getting with regard to this error, please?

**Comment by veb7vmehra** [comment]
The corrections are not able to clear the tests maybe because tests are not designed to clear with such kind of error statements.

**Comment by psesh** [comment]
Can you please submit a pull request for just `poly.py` and `test_poly.py` please? Your pull request #221 has 58 files that have been altered. Also, if there is a specific error that is the issue, please copy it here, so others can also view. Cheers!
