### ISSUE TITLE
Double checking vegetation parameter space

### ISSUE THREAD

**Issue by tarankalra** [Effective-Quadratures/Effective-Quadratures#61]
Can you double check the vegetation input parameter space ? 

 27  [  1.44300000e+02,   2.35000000e-01,   6.00000000e-03,   6.00000000e-04],
 28  [  6.21152934e+01,   1.74581460e-01,   2.90161332e-03,   6.00000000e-04],
 29  [  2.26484707e+02,   2.95418540e-01,   6.00000000e-03,   2.90161332e-04],
 30  [  1.44300000e+02,   1.74581460e-01,   9.09838668e-03,   9.09838668e-04],
 31  [  1.44300000e+02,   2.95418540e-01,   2.90161332e-03,   9.09838668e-04],
 32  [  6.21152934e+01,   2.95418540e-01,   6.00000000e-03,   2.90161332e-04],
 33  [  2.26484707e+02,   1.74581460e-01,   6.00000000e-03,   2.90161332e-04],
 34  [  1.44300000e+02,   2.95418540e-01,   9.09838668e-03,   9.09838668e-04],
 35  [  1.44300000e+02,   2.35000000e-01,   9.09838668e-03,   2.90161332e-04],
 36  [  2.26484707e+02,   2.35000000e-01,   6.00000000e-03,   9.09838668e-04],
 37  [  1.44300000e+02,   2.35000000e-01,   2.90161332e-03,   2.90161332e-04],
 38  [  6.21152934e+01,   2.35000000e-01,   6.00000000e-03,   9.09838668e-04],
 39  [  6.21152934e+01,   1.74581460e-01,   6.00000000e-03,   2.90161332e-04],
 40  [  6.21152934e+01,   2.35000000e-01,   9.09838668e-03,   6.00000000e-04],
 41  [  1.44300000e+02,   1.74581460e-01,   2.90161332e-03,   9.09838668e-04]])

**Comment by psesh** [comment]
Double checked it with mine. Seems alright.
