### ISSUE TITLE
Plotting a parameter issues matplotlib warning

### ISSUE THREAD

**Issue by hertzsprung** [Effective-Quadratures/Effective-Quadratures#95]
Running the jupyter notebook http://nbviewer.jupyter.org/github/Effective-Quadratures/Effective-Quadratures/blob/master/ipython-notebooks/PolynomialChaosPDFs.ipynb gives a warning when plotting `Parameter`s:

```
usr/local/lib/python2.7/dist-packages/equadratures-5.1-py2.7.egg/equadratures/plotting.py:168: MatplotlibDeprecationWarning: The set_axis_bgcolor function was deprecated in version 2.0. Use set_facecolor instead.
  ax.set_axis_bgcolor('whitesmoke')
```

**Comment by psesh** [comment]
Can you commit this notebook to your forked version of the code and send me a link to this notebook please? Cheers!

**Comment by psesh** [comment]
@hertzsprung can you get back to me on this please :) Cheers!
